name: cm_vendor_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  auto_route: ^8.3.0
  provider: ^6.1.2
  easy_localization: ^3.0.7
  json_annotation: ^4.9.0
  dio: ^5.7.0
  logger: ^2.4.0
  japx: ^2.2.0
  copy_with_extension: ^6.0.0
  tuple: ^2.0.2
  os_detect: ^2.0.1
  shared_preferences: ^2.3.5
  package_info_plus: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  copy_with_extension_gen: ^6.0.0

flutter:
  uses-material-design: true
  # list giving the asset and other descriptors for the font. For
  # example:
  assets:
    - assets/translations/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
